name: arenapp
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # Onboard Page, Chat Page
  animated_text_kit: ^4.2.1
  # Onboard Page
  smooth_page_indicator: ^1.0.0+2
  # Onboard Page
  shared_preferences: ^2.0.12
  # Onboard Page, ChatPage
  lottie: ^2.1.0
  # ChatPage
  permission_handler: ^10.0.0
  # Drawer
  font_awesome_flutter: ^10.1.0
  # Database
  path_provider: ^2.0.11
  expandable: ^5.0.1
  # Chat Page
  speech_to_text: ^6.1.0
  # Database
  sqflite: ^2.2.2
  # OpenAI
  dio: ^4.0.6
  # Create Solution
  custom_radio_grouped_button: ^2.1.2+2
  flutter_svg: ^1.1.6
  dotted_border: ^2.0.0+3
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  firebase_storage: ^11.0.10
  cloud_firestore: ^4.3.1
  google_sign_in: ^5.4.3
  provider: ^6.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  image_path: "assets/images/logo.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#297739"
  adaptive_icon_foreground: "assets/images/logo_foreground.png"

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/jsons/


  fonts:
    - family: UbuntuMono
      fonts:
        - asset: assets/fonts/UbuntuMono-Regular.ttf

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf